version: "3.3"
services:
  node:
    tty: true
    stdin_open: true
    container_name: notification-service
    env_file:
      - ./.env
    depends_on:
      - redis
    build: .
    ports:
      - "5050:5050"

  redis:
    image: "redis:6.0.9"